### ISSUE TITLE
Minify js file

### ISSUE THREAD

**Issue by davistan** [RocketChat/WordPressPlugin#13]
Inspecting pagespeed score using https://developers.google.com/speed/pagespeed/insights/ shows below:

```
Minifying https://…t/public/external_api.js?_=1483942093022 could save 1.5KiB (45% reduction) after compression.
```

Is there a way to minify this?

p/s: FYI, the website is already running on W3 Total Cache that does the combine+minify.

**Comment by mbanusic** [comment]
Hi @davistan, that is not something in the plugin. That file is from the Rocket.Chat and should be minified there (if possible). That is not something that W3 or anything in WordPress can actually do. Please file an issues at the [Rocket.Chat project](https://github.com/RocketChat/Rocket.Chat) or try to find appropriate minify options in the Rocket.Chat
