### ISSUE TITLE
Is this plugin compatibilible with WordPress 4.9?

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/WordPressPlugin#15]
> Hello, Rocket.Chat!
> 
> WordPress 4.9 is scheduled to be released on November 14. Are your plugins ready?
> 
> After testing your plugins and ensuring compatibility, it only takes a few moments to change the readme "Tested up to:" value to 4.9. This information provides peace of mind to users and helps encourage them to update to the latest version.
> 
> Here are the current "Tested up to:" values for each of your plugins:
> 
> * https://wordpress.org/plugins/rocketchat-livechat/ (tested up to 4.6.8)
> 
> For each plugin that is compatible, you don't need to release a new version — just change the stable version's readme value.
> 
> Looking to get more familiar with 4.9? Check out this roundup post on the core development blog: https://make.wordpress.org/core/2017/11/07/wordpress-4-9-field-guide/
> 
> Thank you for all you do for the WordPress community, and we hope you enjoy 4.9 as much as we do.
> 
> WordPress core contributors

**Comment by mbanusic** [comment]
Yes it is. I will push the update to mark it "Tested up to".

**Comment by sampaiodiego** [comment]
awesome.. thx
