### ISSUE TITLE
Livechat doesn't show up on Website

### ISSUE THREAD

**Issue by ybshin** [RocketChat/WordPressPlugin#21]
Rocketchat version: 2.0.0
Wordpress version: 4.9.11
Nginx version: 1.15.7
PHP version: 7.2.16

After update Rocketchat, Livechat doesn't show up on our website.

If I type livechat address on chorme, it works.
(https://example.com/livechat/)

**Comment by saschafoerster** [comment]
+1

**Comment by renatobecker-zz** [comment]
@ybshin You need to update the Javascript snippet installation on your website.
We've removed the `1.0.0` from the public path, so you need to apply this change as well.

**Comment by mbanusic** [comment]
New code has been updated in e6ac2556f9bef0b50fd4a88d75bf8879e5e71b4a and has also been uploaded to wordpress.org
