### ISSUE TITLE
Support WHMCS OpenID Connect

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/WordPressPlugin#3]
@liveitpros  please expand this. thx

**Comment by insxa** [comment]
Can you make plugin for whmcs ?

**Comment by mbanusic** [comment]
@duohost In theory yes. I did some WHMCS work 4 years ago, and it was relatively easy to make a plugin. Unfortunately I do not have access to WHMCS installation anymore and therefore I am not able to provide support. If you are interested in developing this kind of plugin and have access to WHMCS installation, contact me and we can work out an arrangement.

**Comment by mbanusic** [comment]
There is a plugin for WHMCS [here](https://github.com/mbanusic/rocketchat-whmcs)

**Comment by liveitpros** [comment]
I would be willing to host a development copy of WHMCS for any interested developers who would like to help with the WHMCS features.
