### ISSUE TITLE
Installation Issue WP 4.5 german

### ISSUE THREAD

**Issue by defcon1702** [RocketChat/WordPressPlugin#5]
How to install the wordpress-plugin correctly? After uploading the zip and activating I get this message: 

lic_html/wp-content/plugins/livechat-wordpress/livechat-wordpress.php Encoding: Re-open Use Code Editor Close Save Changes 
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /www/htdocs/XXXXXX/wp-bh2o/wp-content/plugins/WordPressPlugin-master/livechat-wordpress.php:6) in /www/htdocs/XXXXXX/wp-bh2o/wp-content/plugins/WordPressPlugin-master/livechat-wordpress.php on line 30

Any Ideas?

**Comment by jalik** [comment]
I have the same error after installing, I can't configure the plugin, only the "save details" button is visible.

**Comment by MeanderingCode** [comment]
I have a PR out that fixes the encoding error, and possibly the warning. See #8
