### ISSUE TITLE
Plugin crashes site

### ISSUE THREAD

**Issue by MeanderingCode** [RocketChat/WordPressPlugin#7]
The plugin kills the site, erroring out attempting to call a nonexistant fucntion `$this->_process_formData()`

WordPress debug log:

`[31-May-2016 20:35:44 UTC] PHP Fatal error: Call to undefined method RocketChat_LIVEChat::_process_formData() in /home/user/www/wp-content/plugins/rocketchat-livechat/livechat-wordpress.php on line 339`

**Comment by tikmaster** [comment]
15 days later, still the same issue. Any solutions ?

**Comment by engelgabriel** [comment]
Duplicate of #10 ?

**Comment by mbanusic** [comment]
Plugin at the master branch doesn't work, new one in the develop branch works. We will later move  to the master as development progresses
